scrape_configs: 
  - job_name: "node_exporter"
    dockerswarm_sd_configs: 
      - host: tcp://tasks.socket-proxy:2375
        role: tasks                           # Docker Swarm tasks discovery
        port: 9100 
    relabel_configs:
      - source_labels: [__meta_dockerswarm_task_desired_state]
        regex: running
        action: keep
      - source_labels: [__meta_dockerswarm_service_name]  
        regex: .+_node-exporter$
        action: keep
      - source_labels: [__meta_dockerswarm_node_hostname] 
        target_label: instance
        action: replace