- name: Portainer swarm stack play
  hosts: all
  # connection: local
  become: true

  vars:
    nolog_flag: false  # Global variable to control logging

  tasks:
    - name: ping
      ansible.builtin.ping:

    - name: install dependencies 
      ansible.builtin.dnf:
        state: latest
        name:
          - python3
          - python3-pip

    - name: Install pip dependencies
      ansible.builtin.pip:
        name:
          - hvac # HCP Vault 
          - docker
          - PyYAML
          - jsondiff

#################################################################################
    - name: Get info on Docker Swarm
      community.docker.docker_swarm_info:
      ignore_errors: true
      register: result

    - name: Check if the node is compatible
      ansible.builtin.fail:
        msg: "This host does not seem to be a swarm manager. Exiting."
      when: not (result.can_talk_to_docker and result.docker_swarm_active and result.docker_swarm_manager)

#################################################################################

    - name: Transfer Vault secret to Swarm secret
      community.docker.docker_secret:
        name: OIDC_CLIENT_ID
        data: "{{ lookup('community.hashi_vault.vault_kv2_get', 'stack-110-prometheus/secrets', engine_mount_point='secret').secret.OIDC_CLIENT_ID | b64encode}}"
        data_is_b64: true
        state: present

    - name: Transfer Vault secret to Swarm secret
      community.docker.docker_secret:
        name: OIDC_SECRET_ID
        data: "{{ lookup('community.hashi_vault.vault_kv2_get', 'stack-110-prometheus/secrets', engine_mount_point='secret').secret.OIDC_SECRET_ID | b64encode}}"
        data_is_b64: true
        state: present

    - name: Transfer Vault secret to Swarm secret
      community.docker.docker_secret:
        name: TELEGRAM_BOT_TOKEN
        data: "{{ lookup('community.hashi_vault.vault_kv2_get', 'stack-110-prometheus/secrets', engine_mount_point='secret').secret.TELEGRAM_BOT_TOKEN | b64encode}}"
        data_is_b64: true
        state: present

